//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuplementsShopModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faktura
    {
        public int Faktura_Id { get; set; }
        public System.DateTime TerminPlatnosci { get; set; }
        public double Naleznosc { get; set; }
        public bool Oplacona { get; set; }
        public System.DateTime TerminOplacenia { get; set; }
        public int Klient_Id { get; set; }
        public int Zamowienie_Id { get; set; }
    
        public virtual Klient Klient { get; set; }
        public virtual Zamowienie Zamowienie { get; set; }
    }
}
