//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuplementsShopModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klient
    {
        public Klient()
        {
            this.Faktura = new HashSet<Faktura>();
            this.Zamowienie = new HashSet<Zamowienie>();
        }
    
        public int Id { get; set; }
        public string Status { get; set; }
        public int LimitKredytowy { get; set; }
        public int SaldoZadluzenia { get; set; }
    
        public virtual ICollection<Faktura> Faktura { get; set; }
        public virtual ICollection<Zamowienie> Zamowienie { get; set; }
    }
}
