//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuplementsShopModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producent
    {
        public Producent()
        {
            this.Produkt = new HashSet<Produkt>();
        }
    
        public int Id { get; set; }
        public string NazwaProducenta { get; set; }
    
        public virtual ICollection<Produkt> Produkt { get; set; }
    }
}
