//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuplementsShopModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkt
    {
        public Produkt()
        {
            this.ProduktyKategorii = new HashSet<ProduktyKategorii>();
            this.ProduktyZamówienia = new HashSet<ProduktyZamówienia>();
        }
    
        public int Id { get; set; }
        public string NazwaProduktu { get; set; }
        public double CenaProduktu { get; set; }
        public double WagaProduktu { get; set; }
        public Nullable<System.DateTime> DataDodaniaProduktu { get; set; }
        public int Producent_Id { get; set; }
    
        public virtual Producent Producent { get; set; }
        public virtual ICollection<ProduktyKategorii> ProduktyKategorii { get; set; }
        public virtual ICollection<ProduktyZamówienia> ProduktyZamówienia { get; set; }
    }
}
