//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuplementsShopModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Przesylka
    {
        public Przesylka()
        {
            this.Zamowienie = new HashSet<Zamowienie>();
        }
    
        public int Przesylka_Id { get; set; }
        public bool PotwierdzoneDostarczenie { get; set; }
        public int Wartosc { get; set; }
        public int AdresDostawy { get; set; }
    
        public virtual Adres Adres { get; set; }
        public virtual ICollection<Zamowienie> Zamowienie { get; set; }
    }
}
