//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuplementsShopModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zamowienie
    {
        public Zamowienie()
        {
            this.Faktura = new HashSet<Faktura>();
            this.ProduktyZamowienia = new HashSet<ProduktyZamowienia>();
        }
    
        public int Zamowienie_Id { get; set; }
        public double Wartosc { get; set; }
        public System.DateTime CzasRejestracji { get; set; }
        public System.DateTime TerminRealizacji { get; set; }
        public double Przedplata { get; set; }
        public bool Odrzucone { get; set; }
        public int LiczbaProduktow { get; set; }
        public int AdresRealizacji { get; set; }
        public int Klient_Id { get; set; }
        public int Przesylka_Id { get; set; }
    
        public virtual Adres Adres { get; set; }
        public virtual ICollection<Faktura> Faktura { get; set; }
        public virtual Klient Klient { get; set; }
        public virtual ICollection<ProduktyZamowienia> ProduktyZamowienia { get; set; }
        public virtual Przesylka Przesylka { get; set; }
    }
}
